apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/emmiduh/DevSecOps-CI-CD-Pipeline.git'
    path: apps/monitoring
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
